name: Publish

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-dotnet@v1

    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1

    - name: Nuget Add apiKey 
      run: nuget setapikey ${{ secrets.NUGET_ORG_TOKEN }} -Source "https://api.nuget.org/v3/index.json"

    - name: Nuget Restore 
      run: nuget restore .\CQRSlite.Ninject.Binding.sln

    - name: Build Solution
      run: dotnet build .\CQRSlite.Ninject.Binding.sln --configuration Release

    - name: Nuget Pack
      run: nuget pack .\pack.nuspec -Properties Configuration=Release -OutputDirectory .\nugetPackages -Symbols -SymbolPackageFormat snupkg 
      
    - name: Nuget Push
      run: nuget push .\nugetPackages\*.nupkg -Source "https://api.nuget.org/v3/index.json" -SkipDuplicate -NoSymbols

    - name: Nuget Push2
      run: nuget push .\nugetPackages\*.nupkg -Source GitHub -SkipDuplicate
